/**
 * apiRunner.test.ts
 *
 * ╔══════════════════════════════════════════════════════════════════╗
 * ║  DO NOT EDIT THIS FILE                                           ║
 * ║                                                                  ║
 * ║  This is the generic API test runner.                            ║
 * ║  It reads every flow from apiRegistry.xlsx and runs it.          ║
 * ║                                                                  ║
 * ║  To add, modify or disable a test:                               ║
 * ║    1. Edit data/api/apiRegistry.xlsx                             ║
 * ║    2. Create/edit data/api/assertions/<your-file>.assert.txt     ║
 * ║    3. Run: npx playwright test --project=api                     ║
 * ║                                                                  ║
 * ║  No TypeScript required.                                         ║
 * ╚══════════════════════════════════════════════════════════════════╝
 */

import * as fs   from 'fs';
import * as path from 'path';
import { test, expect } from '../../api/fixtures/apiTest';
import { ApiTestFlow }  from '../../types/ApiTestData';

// ─── Load registry ────────────────────────────────────────────────────────────

const REGISTRY_PATH = path.join(__dirname, '../../data/api/apiRegistry.json');

if (!fs.existsSync(REGISTRY_PATH)) {
    throw new Error(
        `[apiRunner] apiRegistry.json not found at "${REGISTRY_PATH}".\n` +
        `  Run npx playwright test once to trigger apiGlobalSetup and generate it.`
    );
}

const { flows }: { flows: ApiTestFlow[] } = JSON.parse(
    fs.readFileSync(REGISTRY_PATH, 'utf-8')
);

if (!flows || flows.length === 0) {
    throw new Error(
        `[apiRunner] No flows found in apiRegistry.json.\n` +
        `  Ensure apiRegistry.xlsx has rows with Run=TRUE.`
    );
}

// ─── Generic runner ───────────────────────────────────────────────────────────
// One test per flow. Test name = FlowID + Description of first test step.
// Everything else — requests, chaining, assertions — is driven by the registry.

for (const flow of flows) {

    // Build a human-readable test title from the flow
    const firstTestStep = flow.test[0] ?? flow.setup[0];
    const title         = firstTestStep
        ? `${flow.flowId}: ${firstTestStep.registry.Description}`
        : flow.flowId;

    // Collect tags from all steps for --grep filtering
    // e.g. npx playwright test --project=api --grep "@smoke"
    const allTags = [
        ...new Set(
            [...flow.setup, ...flow.test, ...flow.teardown]
                .flatMap(s => s.registry.Tags
                    ? s.registry.Tags.split(',').map(t => t.trim())
                    : []
                )
        )
    ].join(' ');

    //const testTitle = allTags ? `${title} ${allTags}` : title;
    // After
    const firstStep   = flow.test[0] ?? flow.setup[0] ?? flow.teardown[0];
    const priority    = firstStep?.registry?.Priority ?? '';
    const priorityTag = priority && priority !== 'N/A' ? ` @${priority}` : '';
    const testTitle   = allTags ? `${title} ${allTags}${priorityTag}` : `${title}${priorityTag}`;

    test(testTitle, async ({ runFlow }) => {
            // If every step is skipped, mark the whole test as skipped
        const allSteps = [...flow.setup, ...flow.test, ...flow.teardown];
        const allSkipped = allSteps.every(s => (s as any).skipped === true);
        if (allSkipped) {
            test.skip(true, 'All steps disabled (Run=FALSE)');
            return;
        }
        const result = await runFlow(flow.flowId);

        // ── Collect all failures across all steps ─────────────────────────────
        if (!result.allPassed) {
            const failureSummary = result.steps
                .filter(s => !s.skipped && !s.assertions.allPassed)
                .map(step => {
                    const stepHeader = `\n  ✕ [${step.stepId}] ${step.description}` +
                        `\n    Status: ${step.response.status}` +
                        `  Time: ${step.response.responseTime}ms`;

                    const assertionLines = step.assertions.failed
                        .map(f => `\n    ✗ ${f.rule}\n      ${f.message ?? ''}`)
                        .join('');

                    return stepHeader + assertionLines;
                })
                .join('\n');

            throw new Error(`Flow "${flow.flowId}" failed:${failureSummary}`);
        }

        // ── All assertions passed ─────────────────────────────────────────────
        expect(result.allPassed).toBe(true);
    });
}
